version: '3.8'

services:
  mssql:
    build:
      context: dev/database
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'NiezleHaslo123!'
      DATABASE_PASSWORD: 'NiezleHaslo123!'
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '1144:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'dbo'
      MYSQL_USER: 'renting'
      MYSQL_PASSWORD: 'NiezleHaslo123!'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  mssql-data:
  mysql-data:
