version: '3.8'

services:

  mssql:
    build:
      context: dev/database
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'NiezleHaslo123!'
      DATABASE_PASSWORD: 'NiezleHaslo123!'
    networks:
      - bike-renting

  backend:
    build:
      context:  .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      WAIT_HOSTS: mssql:1433
    depends_on:
      - mssql
    ports:
      - '8080:8080'
    networks:
      - bike-renting

volumes:
  mssql-data:


networks:
  bike-renting:
    external: true