version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'dbo'
      MYSQL_USER: 'renting'
      MYSQL_PASSWORD: 'NiezleHaslo123!'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: mysql
    depends_on:
      - mysql
    ports:
      - 8080:8080

volumes:
  mysql-data:
