name: Java CI with Gradle

on:
  push:
    branches: [ to-niezly-branch-pl ]

jobs:

  build:
  
    environment: 'example'
    
    runs-on: ubuntu-20.04

    steps:
    
    - name: checkout
      uses: actions/checkout@v2
   
    - name: Update gradle
      id: gradleUpdate
      uses: EdwarDDay/upgrade-gradle-action@v1
    
    - name: Build NiezlyBackendPL image
      run: ./gradlew :NiezlyBackendPL:dockerBuild -xtest

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
