name: Java CI with Gradle

on:
  push:
    branches: [ to-niezly-branch-pl ]

jobs:

  build:
  
    environment: 'example'
    
    runs-on: ubuntu-latest

    steps:
    
    #setup jdk
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: gradle/wrapper-validation-action@v1.0.3

    - name: Build NiezlyBackendPL image
      run: ./gradlew :NiezlyBackendPL:build -xtest

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
