name: Java CI with Gradle

on:
  push:
    branches: [ to-niezly-branch-pl ]

jobs:

  build-and-push:
  
    environment: 'example'
    
    runs-on: ubuntu-20.04

    steps:
    
    - name: checkout
      uses: actions/checkout@v2
   
    - name: Update gradle
      id: gradleUpdate
      uses: EdwarDDay/upgrade-gradle-action@v1
    
    - name: Build NiezlyBackendPL image
      run: ./gradlew :NiezlyBackendPL:dockerBuild -xtest
    
    - name: Push created image to GCR
      uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
      with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: niezly-backend-pl
          image_tag: latest
          
    - name: Push created image to GCR
      run: |
        docker login -u _json_key -p '${{ secrets.GCLOUD_SERVICE_KEY }}' 'https://gcr.io' 2>/dev/null\
          docker push 'niezly-backend-pl:latest'
          
    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
