# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# MySQL config from: https://github.com/mirromutth/mysql-action

name: Java CI with Maven

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  build:
  
    environment: 'example'
    
    runs-on: ubuntu-latest

    steps:
    
    #setup jdk
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    #Reboot MySQL        
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 1143
        container port: 1143
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql database: 'tests' # Optional, default value is "test". The specified database which will be create        
        mysql user: 'renting' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.DATABASEPASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dskip.npm -Dmaven.test.skip=true
    - name: Run Flyway migrations
      run: ./scripts/flyway.sh tests migrate
    - name: Test with Maven
      run: mvn test
